import localFont from "next/font/local";
import "./globals.css";

import { RecurrenceProvider } from "./context/RecurrenceContext";
import SideBar from "./components/SideBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({Component, pageProps ,children }) {
  return (
    <html lang="en">
      <body className="flex bg-gray-100"> {/* Set background color and flex layout */}
        <RecurrenceProvider>
          <SideBar />
          
          <div className="flex-1 p-4"> 
          {children}
          </div>
        </RecurrenceProvider>
      </body>
    </html>
  );
}
